### ISSUE TITLE
Debugging with hardware debugger

### ISSUE THREAD

**Issue by alexm622** [GorgonMeducer/Pico_Template#2]
I currently in possession of a ULINK2 debugger, do you have any idea on how to debug a pi pico with it? Right now i've got it to detect the arm core but every time i attempt to debug it says "invalid ROM table"

**Comment by GorgonMeducer** [comment]
If you are using MDK, it is impossible to debug pico with ULINK(or any other debugger adapter including jlink). This is because debugging pico require a feature called multi-drop SWD, which MDK simply doesn't support. 

The pico-debug project turns one m0+ core into a cmsis-dap hence bypass this issue. 

I hope this answers your question.

**Comment by alexm622** [comment]
this helps, thank you.

**Comment by Hemistic** [comment]
我想写一个下载算法FLM，可以用另一个pico在mdk中swd下载吗？

**Comment by GorgonMeducer** [comment]
如果你写了下载算法，不需要额外的（也就是你说的另一个Pico），就可以在MDK中下载。

**Comment by Hemistic** [comment]
@GorgonMeducer 
你好，我刚才用picoprobe的swd下载keil生成的axf文件失败，想问一下是怎么回事，我把后缀改成.elf也不行，但是下载cmake出来的elf就没问题，是不是需要将axf文件转换一下才行？

**Comment by GorgonMeducer** [comment]
@Hemistic 这里不需要用 picoprobe，也不支持Picoprobe，你需要用 README里提到的 [Pico-Debug](https://github.com/majbthrd/pico-debug) 在 DebugInSRAM中下载。

如果你不用 DebugInSRAM，那么用 Pico-Template生成的 axf或者 elf是无法直接使用的，Pico-Template会自动生成 u2f 文件，这个文件是可以正常使用的（拖放进 Pico生成的U盘。）。
