### ISSUE TITLE
How to build without MDK

### ISSUE THREAD

**Issue by samveen** [GorgonMeducer/Pico_Template#6]
My access is limited to Linux, and Keil MDK is limited to MS Win platform as per the download page at developer.arm.com website.

Is it possible to get instructions on how to build the project on the linux command line, like the Pico SDK is used in the pico-examples?

**Comment by GorgonMeducer** [comment]
Hi, thank you for considering using this Pico-Template. Can I know why you want to use this Pico-Template on Linux?
The reason why I am asking this question is because:
- Pico-Template is prepared for people who want to use Pico on MDK 
- Pico-Template allows people to use Pico-SDK in MDK (and use Arm Compiler 6 rather than GCC)

If you are using Linux, it is usually recommended to use the official Pico-SDK cmake project.

**Comment by samveen** [comment]
My use case was to try and reuse https://github.com/spencergotowork/GAME-2D/tree/snake , which is an exact match for that I need. However, as that derivative of your excellent project is MDK based, it is MDK based. 

All my professional and personal work is based on and with Linux, including my experimentation with micro-controllers, including Adafruit's feather, the WeACT Black Pill, and the Pico/Pico W, which makes me very confident that I will be able to solve  issues as I come across them.

With windows, I have no level of comfort or confidence on whether I can even trace issues that crop up.

**Comment by GorgonMeducer** [comment]
@samveen maybe you can check this repo:

https://github.com/AlgoOy/TinySquare/tree/main/examples/snake

**Comment by samveen** [comment]
@GorgonMeducer Thank you for the info. I will.
